##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-power-manager
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libgcrypt20-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libcafe-panel-applet-dev
    - libnotify-dev
    - libpolkit-gobject-1-dev
    - libtool-bin
    - libupower-glib-dev
    - libx11-dev
    - libxext-dev
    - libxml-parser-perl
    - libxrandr-dev
    - make
    - cafe-common
    - pkg-config
    - xmlto
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--without-keyring --enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/${REPO_NAME}/raw/master/data/icons/16x16/apps/cafe-power-manager.png; fi
